import { Employee } from '../types';

export const mockEmployees: Employee[] = [
  {
    id: '1',
    fullName: 'John Doe',
    gender: 'Male',
    dateOfBirth: '1990-05-15',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    state: 'California',
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    fullName: 'Jane Smith',
    gender: 'Female',
    dateOfBirth: '1992-08-22',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    state: 'Texas',
    isActive: true,
    createdAt: '2024-01-16',
  },
  {
    id: '3',
    fullName: 'Michael Johnson',
    gender: 'Male',
    dateOfBirth: '1988-03-10',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    state: 'New York',
    isActive: false,
    createdAt: '2024-01-17',
  },
  {
    id: '4',
    fullName: 'Sarah Williams',
    gender: 'Female',
    dateOfBirth: '1995-11-30',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    state: 'Florida',
    isActive: true,
    createdAt: '2024-01-18',
  },
  {
    id: '5',
    fullName: 'Robert Brown',
    gender: 'Male',
    dateOfBirth: '1987-07-05',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    state: 'Illinois',
    isActive: true,
    createdAt: '2024-01-19',
  },
];

export const indianStates = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];